const FoodMenu = [
    { index: 1, name: "Mixed Meat and Seafood Platter", nameVN: "Combo khai vị thập cẩm", price: 16.80 },
    { index: 2, name: "Vegetarian Platter", nameVN: "Combo khai vị chay", price: 14.80 },
    { index: 3, name: "Spring Rolls", nameVN: "Chả giò", price: 6.80 },
    { index: 4, name: "Vegetable Spring Rolls", nameVN: "Chả giò chay", price: 6.50 },
    { index: 5, name: "Prawn Summer Rolls", nameVN: "Gỏi cuốn tôm", price: 6.50 },
    { index: 6, name: "Beef Summer Rolls", nameVN: "Gỏi cuốn bò", price: 6.80 },
    { index: 7, name: "Tofu Summer Rolls", nameVN: "Gỏi cuốn đậu phụ", price: 6.50 },
    { index: 8, name: "Chicken Wings with Anchovy Sauce", nameVN: "Cánh gà chiên nước mắm", price: 8.50 },
    { index: 9, name: "Crispy Prawns in Batter", nameVN: "Tôm tẩm bột chiên giòn", price: 6.50 },
    { index: 10, name: "Crispy Fried Sweet Corn", nameVN: "Ngô chiên giòn", price: 6.80 },
    { index: 11, name: "Barbecue Grilled Quail", nameVN: "Chim cút nướng", price: 8.80 },
    { index: 12, name: "Deep Fried Pork Intestine, Deep Fried Tofu and Vermicelli", nameVN: "Bún đậu lòng mắm tôm", price: 13.80 },
    { index: 13, name: "Prawn Cracker", nameVN: "Bánh phồng tôm", price: 2.90 },
    { index: 14, name: "Salt & Pepper Squid", nameVN: "Mực rang muối tiêu", price: 9.50 },
    { index: 15, name: "Salt & Pepper Prawns", nameVN: "Tôm rang muối tiêu", price: 9.50 },
    { index: 16, name: "Salt & Pepper Chicken Wings", nameVN: "Cánh gà rang muối tiêu", price: 8.50 },
    { index: 17, name: "Salt & Pepper Chicken Feet", nameVN: "Chân gà rang muối tiêu", price: 9.50 },
    { index: 18, name: "Salt & Pepper Frog Legs", nameVN: "Đùi ếch rang muối tiêu", price: 10.50 },
    { index: 19, name: "Salt & Pepper Tofu", nameVN: "Đậu phụ rang muối tiêu", price: 7.80 },
    { index: 20, name: "Salt & Pepper Chips", nameVN: "Khoai tây rang muối tiêu", price: 5.50 },
    { index: 21, name: "Stir-fried Morning Glory with Garlic", nameVN: "Rau muống xào tỏi", price: 9.25 },
    { index: 22, name: "Stir-fried Pak Choi with Garlic", nameVN: "Rau cải xào tỏi", price: 8.80 },
    { index: 23, name: "Stir-fried Stem Broccoli with Garlic", nameVN: "Bông cải xanh xào tỏi", price: 8.80 },
    { index: 24, name: "Wok Fried Fine Beans with Garlic", nameVN: "Đậu đũa xào tỏi", price: 8.80 },
    { index: 25, name: "Prawn Mango Salad", nameVN: "Nộm tôm xoài", price: 9.50 },
    { index: 26, name: "Jellyfish Mango Salad", nameVN: "Nộm sứa xoài", price: 10.50 },
    { index: 27, name: "Chicken Salad", nameVN: "Nộm gà", price: 8.80 },
    { index: 28, name: "Beef Salad", nameVN: "Nộm bò", price: 9.50 },
    { index: 29, name: "Chicken Feet Salad", nameVN: "Nộm chân gà", price: 8.80 },
    { index: 30, name: "Tofu and Mixed Vegetable Salad", nameVN: "Nộm chay đậu phụ", price: 9.50 },
    { index: 31, name: "Grilled Pork Marinated with Lemongrass Banh Mi", nameVN: "Bánh mì thịt nướng", price: 7.50 },
    { index: 32, name: "Grilled Chicken Marinated with Lemongrass Banh Mi", nameVN: "Bánh mì gà nướng", price: 7.50 },
    { index: 33, name: "Special Banh Mi (Pate, Pork Sausage and VietNamese Ham)", nameVN: "Bánh mì đặc biệt", price: 8.50 },
    { index: 34, name: "Crispy Roasted Pork Banh Mi", nameVN: "Bánh mì heo quay giòn bì", price: 8.90 },
    { index: 35, name: "Fried Tofu Banh Mi", nameVN: "Bánh mì đậu phụ", price: 6.95 },
    { index: 36, name: "Slow Cooked Brisket Beef Pho", nameVN: "Phở bò chín", price: 11.25 },
    { index: 37, name: "Sliced Rare Beef Pho", nameVN: "Phở bò tái", price: 11.25 },
    { index: 38, name: "Slow Cooked Brisket Beef and Sliced Rare Beef Pho", nameVN: "Phở bò chín và tái", price: 12.80 },
    { index: 39, name: "Stir Fried Beef with Garlic Pho", nameVN: "Phở bò tái lăn", price: 12.80 },
    { index: 40, name: "Stewed Brisket Beef Pho", nameVN: "Phở bò kho", price: 12.80 },
    { index: 41, name: "Pulled Chicken Pho", nameVN: "Phở gà", price: 11.25 },
    { index: 42, name: "King Prawn Pho", nameVN: "Phở tôm", price: 12.80 },
    { index: 43, name: "Special Pho (King prawn, chicken, slow cooked brisket beef and sliced rare beef)", nameVN: "Phở đặc biệt (tôm, gà, bò chín, bò tái)", price: 12.80 },
    { index: 44, name: "Mixed Seafood Pho (King prawn, squid, green mussels)", nameVN: "Phở hải sản (tôm, mực, vẹm xanh)", price: 12.80 },
    { index: 45, name: "Tofu and Mixed Vegetables Pho (Vegan broth)", nameVN: "Phở chay", price: 10.80 },
    { index: 46, name: "Slow Cooked Brisket Beef Bun Hue", nameVN: "Bún bò Huế", price: 11.50 },
    { index: 47, name: "Slow Cooked Brisket Beef, Pig Trotters, Traditional Homemade Pork Sausage Bun Hue", nameVN: "Bún bò giò heo", price: 12.80 },
    { index: 48, name: "Chicken Bun Hue", nameVN: "Bún gà Huế", price: 11.25 },
    { index: 49, name: "King Prawn Bun Hue", nameVN: "Bún tôm Huế", price: 12.80 },
    { index: 50, name: "Fried Sliced Sea Bass Fillet, Homemade Fish Cake & Tofu Bun Hue", nameVN: "Bún cá cay (cá chiên, chả cá, đậu phụ)", price: 13.80 },
    { index: 51, name: "Special Bun Hue (King prawn, chicken, slow cooked brisket beef & sliced rare beef)", nameVN: "Bún Huế đặc biệt (tôm, gà, bò chín, bò tái)", price: 12.80 },
    { index: 52, name: "Mixed Seafood Bun Hue (King prawn, squid, green mussels)", nameVN: "Bún hải sản Huế (tôm, mực, vẹm xanh)", price: 12.80 },
    { index: 53, name: "Tofu & Mixed Vegetable Bun Hue", nameVN: "Bún chay Huế", price: 11.25 },
    { name: "Extra Topping - Flat Rice Noodle", nameVN: "Bánh phở", price: 1.95 },
    { name: "Extra Topping - Vermicelli Noodle", nameVN: "Bún", price: 1.95 },
    { name: "Extra Topping - Rare Beef", nameVN: "Thịt bò tái", price: 2.95 },
    { name: "Extra Topping - Slow Cooked Brisket Beef", nameVN: "Thịt bò chín", price: 2.95 },
    { name: "Extra Topping - Chicken", nameVN: "Thịt gà", price: 2.95 },
    { name: "Extra Topping - King Prawn", nameVN: "Tôm", price: 2.95 },
    { name: "Extra Topping - Squid", nameVN: "Mực", price: 2.95 },
    { name: "Extra Topping - Mussel", nameVN: "Vẹm xanh", price: 2.95 },
    { name: "Extra Topping - Fried Egg", nameVN: "Trứng chiên", price: 1.20 },
    { name: "Extra Topping - Beansprouts, Chillies & Herbs", nameVN: "Giá, ớt và rau thơm", price: 1.00 },
    { index: 54, name: "Grilled Pork Marinated with Lemongrass Bun", nameVN: "Bún thịt nướng", price: 10.80 },
    { index: 55, name: "Grilled Pork & Meat Spring Rolls Bun", nameVN: "Bún chả nem thịt nướng", price: 12.80 },
    { index: 56, name: "Meat Spring Rolls Bun", nameVN: "Bún chả nem thịt", price: 10.80 },
    { index: 57, name: "Tofu & Mixed Vegetable Spring Rolls Bun", nameVN: "Bún chả nem chay đậu phụ", price: 10.80 },
    { index: 58, name: "Grilled Chicken Marinated with Lemongrass Bun", nameVN: "Bún gà nướng", price: 10.80 },
    { index: 59, name: "Stir Fried Chicken with Lemongrass & Chillies Bun", nameVN: "Bún gà xào sả ớt", price: 10.80 },
    { index: 60, name: "Stir Fried Beef with Lemongrass & Chillies Bun", nameVN: "Bún bò xào sả ớt", price: 11.25 },
    { index: 61, name: "Stir Fried King Prawn with Lemongrass & Chillies Bun", nameVN: "Bún tôm xào sả ớt", price: 12.80 },
    { index: 62, name: "Stir Fried Tofu with Lemongrass & Chillies Bun", nameVN: "Bún đậu phụ xào sả ớt", price: 10.80 },
    { index: 63, name: "Grilled Pork Marinated with Lemongrass Rice", nameVN: "Cơm thịt nướng", price: 10.80 },
    { index: 64, name: "Grilled Chicken Marinated with Lemongrass Rice", nameVN: "Cơm gà nướng", price: 10.80 },
    { index: 65, name: "Grilled Pork Chop with Lemongrass, Fried Egg and Rice", nameVN: "Cơm sườn nướng, trứng chiên", price: 13.80 },
    { index: 66, name: "Vietnamese Stewed Pork Belly with Egg and Rice", nameVN: "Cơm thịt kho trứng", price: 13.80 },
    { index: 67, name: "Vietnamese Stewed Beef Rice", nameVN: "Cơm bò kho", price: 12.80 },
    { index: 68, name: "Roasted Crispy Pork Rice", nameVN: "Cơm thịt heo quay giòn bì", price: 13.80 },
    { index: 69, name: "Chicken Fried Rice", nameVN: "Cơm chiên gà", price: 11.25 },
    { index: 70, name: "Beef Fried Rice", nameVN: "Cơm chiên bò", price: 11.25 },
    { index: 71, name: "King Prawn Fried Rice", nameVN: "Cơm chiên tôm", price: 12.80 },
    { index: 72, name: "Mixed Meat Fried Rice (King prawn, chicken and beef)", nameVN: "Cơm chiên đặc biệt (tôm, gà, bò)", price: 12.80 },
    { index: 73, name: "Mixed Seafood Fried Rice (King prawn, squid and mussels)", nameVN: "Cơm chiên hải sản (tôm, mực, vẹm)", price: 12.80 },
    { index: 74, name: "Tofu & Mixed Vegetable Fried Rice", nameVN: "Cơm chiên chay đậu phụ", price: 10.80 },
    { index: 75, name: "Chicken Fried Egg Noodles", nameVN: "Mì xào thịt gà", price: 11.25 },
    { index: 76, name: "Beef Fried Egg Noodles", nameVN: "Mì xào thịt bò", price: 11.25 },
    { index: 77, name: "King Prawn Fried Egg Noodles", nameVN: "Mì xào tôm", price: 12.80 },
    { index: 78, name: "Special Fried Egg Noodles (King prawn, chicken & beef)", nameVN: "Mì xào đặc biệt (tôm, gà, bò)", price: 12.80 },
    { index: 79, name: "Mixed Seafood Fried Egg Noodles (King prawn, squid & mussels)", nameVN: "Mì xào hải sản (tôm, mực, vẹm)", price: 12.80 },
    { index: 80, name: "Bean Sprouts & Onions Fried Egg Noodles", nameVN: "Mì xào giá", price: 7.80 },
    { index: 81, name: "Tofu & Mixed Vegetable Fried Egg Noodles", nameVN: "Mì xào chay đậu phụ", price: 10.80 },
    { index: 82, name: "Chicken Fried Flat Rice Noodles", nameVN: "Phở xào thịt gà", price: 11.25 },
    { index: 83, name: "Beef Fried Flat Rice Noodles", nameVN: "Phở xào thịt bò", price: 11.25 },
    { index: 84, name: "King Prawn Fried Flat Rice Noodles", nameVN: "Phở xào tôm", price: 12.80 },
    { index: 85, name: "Special Fried Flat Rice Noodles (King prawn, chicken & beef)", nameVN: "Phở xào đặc biệt (tôm, gà, bò)", price: 12.80 },
    { index: 86, name: "Mixed Seafood Fried Flat Rice Noodles (King prawn, squid & mussels)", nameVN: "Phở xào hải sản (tôm, mực, vẹm)", price: 12.80 },
    { index: 87, name: "Bean Sprouts & Onions Fried Flat Rice Noodles", nameVN: "Phở xào giá", price: 7.80 },
    { index: 88, name: "Tofu & Mixed Vegetable Fried Flat Rice Noodles", nameVN: "Phở xào chay đậu phụ", price: 10.80 },
    { index: 89, name: "Clay Pot Mekong Catfish", nameVN: "Cá kho tộ", price: 12.80 },
    { index: 90, name: "Camfried Beef", nameVN: "Bò lửa hồng", price: 12.80 },
    { index: 91, name: "Shaking Beef", nameVN: "Bò lúc lắc", price: 13.80 },
    { index: 92, name: "Deep Fried Crispy Fillet Sea Bass", nameVN: "Cá chiên mắm xoài", price: 12.80 },
    { index: 93, name: "Vietnamese Fried Squid with Onion, Celery, Tomatoes and Chillies Paste", nameVN: "Mực xào sả ớt", price: 11.80 },
    { index: 94, name: "Stewed Tofu with Mushroom", nameVN: "Đậu phụ kho", price: 10.80 },
    { index: 95, name: "Fried Chicken with Lemongrass and Chillies", nameVN: "Gà xào sả ớt", price: 11.80 },
    { index: 96, name: "Wok Fried Aubergine with Tofu and Chillies Paste", nameVN: "Cà tím, đậu phụ xào cay", price: 10.80 },
    { index: 97, name: "Beef Curry", nameVN: "Cà ri bò", price: 12.80 },
    { index: 98, name: "Chicken Curry", nameVN: "Cà ri gà", price: 11.80 },
    { index: 99, name: "Lamb Curry", nameVN: "Cà ri cừu", price: 13.80 },
    { index: 100, name: "Tofu & Mixed Vegetable Curry", nameVN: "Cà ri chay đậu phụ", price: 11.80 },
    { index: 101, name: "Chicken Fried Rice (Kid)", nameVN: "Cơm rang gà", price: 7.50 },
    { index: 102, name: "Deep Fried Chicken Wings & Chips", nameVN: "Cánh gà khoai tây chiên", price: 7.50 },
    { index: 103, name: "Chicken Pho (Kid)", nameVN: "Phở gà", price: 7.50 },
    { index: 104, name: "Beef Pho (Kid)", nameVN: "Phở bò", price: 7.50 },
    // --- EXTRA DISHES ---
    { name: "Extra dishes - Bowl of Beef Broth with Green Onion", nameVN: "Nước dùng bò với hành lá", price: 1.95 },
    { name: "Extra dishes - Bowl of Beef Broth with Egg Yolk", nameVN: "Nước dùng bò với trứng", price: 2.50 },
    { name: "Extra dishes - Egg in Spicy Soy Sauce (for two)", nameVN: "Trứng sốt tương cay", price: 3.50 },
    { name: "Extra dishes - Jasmine Rice", nameVN: "Cơm trắng", price: 2.90 },
    { name: "Extra dishes - Egg Fried Rice", nameVN: "Cơm chiên trứng", price: 3.90 }
];

const DrinkMenu = [
    // VIETNAMESE COFFEE
    {
        category: "Coffee",
        name: "Rich Vietnamese Hot Coffee",
        nameVN: "Cà phê nóng",
        options: [{ label: "Black", price: 3.50 }, { label: "With milk", price: 3.50 }]
    },
    {
        category: "Coffee",
        name: "Vietnamese Iced Coffee",
        nameVN: "Cà phê đá",
        options: [{ label: "Black", price: 3.50 }, { label: "With milk", price: 3.50 }]
    },

    // TEA
    { category: "Tea", name: "Chamomile", nameVN: "Trà hoa cúc", options: [{ label: "Regular", price: 3.50 }] },
    { category: "Tea", name: "Mint Tea", nameVN: "Trà bạc hà", options: [{ label: "Regular", price: 2.25 }] },
    { category: "Tea", name: "Green Tea", nameVN: "Trà xanh", options: [{ label: "Regular", price: 2.25 }] },
    { category: "Tea", name: "Jasmine Tea", nameVN: "Trà hoa nhài", options: [{ label: "Regular", price: 2.25 }] },
    { category: "Tea", name: "Orange Lemon Grass Peach Tea", nameVN: "Trà đào cam sả", options: [{ label: "Regular", price: 4.00 }] },
    { category: "Tea", name: "Peach Milk Ice Tea", nameVN: "Trà sữa thạch đào", options: [{ label: "Regular", price: 4.00 }] },
    { category: "Tea", name: "Butterfly Pea Tea Lemonade", nameVN: "Trà chanh hoa đậu biếc", options: [{ label: "Regular", price: 3.50 }] },

    //DESSERT
    { category: "Dessert", name: "Classic Vietnam Multi Colours Dessert", nameVN: "Chè thập cẩm", options: [{ label: "Regular", price: 4.50 }] },
    { category: "Dessert", name: "Vietnamese Style Fruit Salad", nameVN: "Hoa quả dầm", options: [{ label: "Regular", price: 4.50 }] },

    // WHITE WINE
    { category: "White Wine", name: "Molino Del Sol Airen (Spain)", nameVN: null, options: [{ label: "175ml", price: 3.50 }, { label: "250ml", price: 5.00 }, { label: "BTL", price: 15.00 }] },
    { category: "White Wine", name: "Umbala Sauvignon Blanc (South Africa)", nameVN: null, options: [{ label: "BTL", price: 16.00 }] },
    { category: "White Wine", name: "Farfalla Pinot Grigio (Italy)", nameVN: null, options: [{ label: "175ml", price: 4.00 }, { label: "250ml", price: 5.75 }, { label: "BTL", price: 17.00 }] },
    { category: "White Wine", name: "Central Monte Chardonnay (Chile)", nameVN: null, options: [{ label: "BTL", price: 17.00 }] },

    // ROSÉ WINE
    { category: "Rosé Wine", name: "Farfalla Pinot Grigio Blush (Italy)", nameVN: null, options: [{ label: "175ml", price: 4.00 }, { label: "250ml", price: 5.75 }, { label: "BTL", price: 17.00 }] },
    { category: "Rosé Wine", name: "Monterey Bay Zinfandel Rose (USA)", nameVN: null, options: [{ label: "BTL", price: 19.00 }] },

    // RED WINE
    { category: "Red Wine", name: "Molino Del Sol Tempranillo (Spain)", nameVN: null, options: [{ label: "175ml", price: 3.50 }, { label: "250ml", price: 5.00 }, { label: "BTL", price: 15.00 }] },
    { category: "Red Wine", name: "Umbala Shiraz (South Africa)", nameVN: null, options: [{ label: "BTL", price: 16.00 }] },
    { category: "Red Wine", name: "Central Monte Merlot (Chile)", nameVN: null, options: [{ label: "BTL", price: 17.00 }] },
    { category: "Red Wine", name: "Equino Malbec (Argentina)", nameVN: null, options: [{ label: "BTL", price: 19.00 }] },

    // SPARKLING WINE
    { category: "Sparkling Wine", name: "Prosecco, Famiglia Botter D.O.C Extra Dry (Italy)", nameVN: null, options: [{ label: "BTL", price: 21.00 }] },
    { category: "Sparkling Wine", name: "Prosecco Rosé, Famiglia Botter D.O.C Extra Dry (Italy)", nameVN: null, options: [{ label: "BTL", price: 22.00 }] },

    // BEER & CIDER
    { category: "Beer & Cider", name: "Hanoi Beer", nameVN: null, options: [{ label: "330ml", price: 4.50 }] },
    { category: "Beer & Cider", name: "Saigon Beer", nameVN: null, options: [{ label: "330ml", price: 4.50 }] },
    { category: "Beer & Cider", name: "Asahi", nameVN: null, options: [{ label: "330ml", price: 4.00 }] },
    { category: "Beer & Cider", name: "Corona Extra", nameVN: null, options: [{ label: "330ml", price: 4.00 }] },
    { category: "Beer & Cider", name: "Stella Artois", nameVN: null, options: [{ label: "275ml", price: 4.00 }] },
    { category: "Beer & Cider", name: "Heineken 0.0% Alc Free", nameVN: null, options: [{ label: "330ml", price: 3.50 }] },
    { category: "Beer & Cider", name: "Kopparberg Mixed Fruit", nameVN: null, options: [{ label: "500ml", price: 5.50 }] },
    { category: "Beer & Cider", name: "Kopparberg Strawberry & Lime", nameVN: null, options: [{ label: "500ml", price: 5.50 }] },

    // COCKTAILS
    { category: "Cocktails", name: "Pornstar Martini", nameVN: null, options: [{ label: "Regular", price: 7.50 }] },
    { category: "Cocktails", name: "Espresso Martini", nameVN: null, options: [{ label: "Regular", price: 7.50 }] },
    { category: "Cocktails", name: "Strawberry Daiquiri", nameVN: null, options: [{ label: "Regular", price: 7.50 }] },
    { category: "Cocktails", name: "Pina Colada", nameVN: null, options: [{ label: "Regular", price: 7.50 }] },

    // MINERALS / SOFT DRINK
    { category: "Soft Drink", name: "Coca Cola", nameVN: null, options: [{ label: "330ml", price: 2.90 }] },
    { category: "Soft Drink", name: "Diet Coke", nameVN: null, options: [{ label: "330ml", price: 2.70 }] },
    { category: "Soft Drink", name: "Marlish Brazilian Orange", nameVN: null, options: [{ label: "330ml Can", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Sicilian Lemon", nameVN: null, options: [{ label: "330ml Can", price: 2.50 }] },
    { category: "Soft Drink", name: "Tomato Juice", nameVN: null, options: [{ label: "Regular", price: 2.50 }] },
    { category: "Soft Drink", name: "Apple Juice", nameVN: null, options: [{ label: "Regular", price: 2.50 }] },
    { category: "Soft Drink", name: "Orange Juice", nameVN: null, options: [{ label: "Regular", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Sparkling Water", nameVN: null, options: [{ label: "330ml", price: 1.95 }, { label: "750ml", price: 3.75 }] },
    { category: "Soft Drink", name: "Marlish Still Water", nameVN: null, options: [{ label: "330ml", price: 1.95 }, { label: "750ml", price: 3.75 }] },
    { category: "Soft Drink", name: "Marlish Soda Water", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish English Tonic", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Premium Lemonade", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Raspberry Tonic", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Distiller's Choice Tonic", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Elderflower Tonic", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Rhubarb Ginger Ale", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },
    { category: "Soft Drink", name: "Marlish Dandelion & Burdock Tonic", nameVN: null, options: [{ label: "200ml", price: 2.50 }] },


    // VODKA & GIN
    { category: "Vodka & Gin", name: "Absolut Vodka", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Vodka & Gin", name: "Smirnoff Vodka", nameVN: null, options: [{ label: "25ml", price: 3.40 }] },
    { category: "Vodka & Gin", name: "Bombay Sapphire Gin", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Vodka & Gin", name: "Gordon's Gin", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Vodka & Gin", name: "Gordon's Pink Gin", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Vodka & Gin", name: "Agnes Arber Rhubarb Gin", nameVN: null, options: [{ label: "25ml", price: 4.95 }] },
    { category: "Vodka & Gin", name: "Agnes Arber Pineapple Gin", nameVN: null, options: [{ label: "25ml", price: 4.95 }] },

    // RUM & TEQUILA
    { category: "Rum & Tequila", name: "Captain Morgan Dark Rum", nameVN: null, options: [{ label: "25ml", price: 3.40 }] },
    { category: "Rum & Tequila", name: "Malibu", nameVN: null, options: [{ label: "25ml", price: 3.40 }] },
    { category: "Rum & Tequila", name: "Bacardi Carta Blanca", nameVN: null, options: [{ label: "25ml", price: 3.40 }] },
    { category: "Rum & Tequila", name: "Old J Spiced Rum", nameVN: null, options: [{ label: "25ml", price: 3.60 }] },
    { category: "Rum & Tequila", name: "Jose Cuervo Gold Tequila", nameVN: null, options: [{ label: "25ml", price: 3.60 }] },

    // WHISKEY
    { category: "Whiskey", name: "Jack Daniels Whiskey", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Whiskey", name: "Johnnie Walker Black Label", nameVN: null, options: [{ label: "25ml", price: 4.95 }] },

    // APERITIFS & LIQUIERS
    { category: "Aperitifs & Liquiers", name: "Baileys", nameVN: null, options: [{ label: "50ml", price: 3.50 }] },
    { category: "Aperitifs & Liquiers", name: "Cointreau", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Aperitifs & Liquiers", name: "Jagermeister", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },
    { category: "Aperitifs & Liquiers", name: "Disaronno Amaretto", nameVN: null, options: [{ label: "25ml", price: 3.50 }] },

    // JUICE
    { category: "Juice", name: "Fresh Lemon Juice", nameVN: "Nước chanh tươi / 柠檬汁", options: [{ label: "Regular", price: 2.95 }] },
    { category: "Juice", name: "Coconut Juice", nameVN: "Nước dừa / 椰子汁", options: [{ label: "Regular", price: 2.95 }] },
];