const menuItems = [
  {index:1, name:"Mixed Meat and Seafood Platter", nameVN:"Món khai vị thịt & hải sản tổng hợp", price:16.80},
  {index:2, name:"Vegetarian Platter", nameVN:"Món khai vị chay tổng hợp", price:14.80},
  {index:3, name:"Spring Rolls", nameVN:"Chả giò", price:6.80},
  {index:4, name:"Vegetable Spring Rolls", nameVN:"Chả giò chay", price:6.50},
  {index:5, name:"Prawn Summer Rolls", nameVN:"Gỏi cuốn tôm", price:6.50},
  {index:6, name:"Beef Summer Rolls", nameVN:"Gỏi cuốn bò", price:6.80},
  {index:7, name:"Tofu Summer Rolls", nameVN:"Gỏi cuốn đậu phụ", price:6.50},
  {index:8, name:"Chicken Wings with Anchovy Sauce", nameVN:"Cánh gà chiên nước mắm", price:8.50},
  {index:9, name:"Crispy Prawns in Batter", nameVN:"Tôm tẩm bột chiên giòn", price:6.50},
  {index:10, name:"Crispy Fried Sweet Corn", nameVN:"Ngô chiên giòn", price:6.80},
  {index:11, name:"Barbecue Grilled Quail", nameVN:"Chim cút nướng", price:8.80},
  {index:12, name:"Deep Fried Pork Intestine, Deep Fried Tofu and Vermicelli", nameVN:"Bún đậu lòng mắm tôm", price:13.80},
  {index:13, name:"Prawn Cracker", nameVN:"Bánh phồng tôm", price:2.90},
  {index:14, name:"Salt & Pepper Squid", nameVN:"Mực rang muối tiêu", price:9.50},
  {index:15, name:"Salt & Pepper Prawns", nameVN:"Tôm rang muối tiêu", price:9.50},
  {index:16, name:"Salt & Pepper Chicken Wings", nameVN:"Cánh gà rang muối tiêu", price:8.50},
  {index:17, name:"Salt & Pepper Chicken Feet", nameVN:"Chân gà rang muối tiêu", price:9.50},
  {index:18, name:"Salt & Pepper Frog Legs", nameVN:"Đùi ếch rang muối tiêu", price:10.50},
  {index:19, name:"Salt & Pepper Tofu", nameVN:"Đậu phụ rang muối tiêu", price:7.80},
  {index:20, name:"Salt & Pepper Chips", nameVN:"Khoai tây rang muối tiêu", price:5.50},
  {index:21, name:"Stir-fried Morning Glory with Garlic", nameVN:"Rau muống xào tỏi", price:9.25},
  {index:22, name:"Stir-fried Pak Choi with Garlic", nameVN:"Rau cải xào tỏi", price:8.80},
  {index:23, name:"Stir-fried Stem Broccoli with Garlic", nameVN:"Bông cải xanh xào tỏi", price:8.80},
  {index:24, name:"Wok Fried Fine Beans with Garlic", nameVN:"Đậu đũa xào tỏi", price:8.80},
  {index:25, name:"Prawn Mango Salad", nameVN:"Nộm tôm xoài", price:9.50},
  {index:26, name:"Jellyfish Mango Salad", nameVN:"Nộm sứa xoài", price:10.50},
  {index:27, name:"Chicken Salad", nameVN:"Nộm gà", price:8.80},
  {index:28, name:"Beef Salad", nameVN:"Nộm bò", price:9.50},
  {index:29, name:"Chicken Feet Salad", nameVN:"Nộm chân gà", price:8.80},
  {index:30, name:"Tofu and Mixed Vegetable Salad", nameVN:"Nộm chay đậu phụ", price:9.50},
  {index:31, name:"Grilled Pork Marinated with Lemongrass Banh Mi", nameVN:"Bánh mì thịt nướng", price:7.50},
  {index:32, name:"Grilled Chicken Marinated with Lemongrass Banh Mi", nameVN:"Bánh mì gà nướng", price:7.50},
  {index:33, name:"Special Banh Mi (Pate, Pork Sausage and VietNamese Ham)", nameVN:"Bánh mì đặc biệt", price:8.50},
  {index:34, name:"Crispy Roasted Pork Banh Mi", nameVN:"Bánh mì heo quay giòn bì", price:8.90},
  {index:35, name:"Fried Tofu Banh Mi", nameVN:"Bánh mì đậu phụ", price:6.95},
  {index:36, name:"Slow Cooked Brisket Beef Pho", nameVN:"Phở bò chín", price:11.25},
  {index:37, name:"Sliced Rare Beef Pho", nameVN:"Phở bò tái", price:11.25},
  {index:38, name:"Slow Cooked Brisket Beef and Sliced Rare Beef Pho", nameVN:"Phở bò chín và tái", price:12.80},
  {index:39, name:"Stir Fried Beef with Garlic Pho", nameVN:"Phở bò tái lăn", price:12.80},
  {index:40, name:"Stewed Brisket Beef Pho", nameVN:"Phở bò kho", price:12.80},
  {index:41, name:"Pulled Chicken Pho", nameVN:"Phở gà", price:11.25},
  {index:42, name:"King Prawn Pho", nameVN:"Phở tôm", price:12.80},
  {index:43, name:"Special Pho (King prawn, chicken, slow cooked brisket beef and sliced rare beef)", nameVN:"Phở đặc biệt (tôm, gà, bò chín, bò tái)", price:12.80},
  {index:44, name:"Mixed Seafood Pho (King prawn, squid, green mussels)", nameVN:"Phở hải sản (tôm, mực, vẹm xanh)", price:12.80},
  {index:45, name:"Tofu and Mixed Vegetables Pho (Vegan broth)", nameVN:"Phở chay", price:10.80},
  {index:46, name:"Slow Cooked Brisket Beef Bun Hue", nameVN:"Bún bò Huế", price:11.50},
  {index:47, name:"Slow Cooked Brisket Beef, Pig Trotters, Traditional Homemade Pork Sausage Bun Hue", nameVN:"Bún bò giò heo", price:12.80},
  {index:48, name:"Chicken Bun Hue", nameVN:"Bún gà Huế", price:11.25},
  {index:49, name:"King Prawn Bun Hue", nameVN:"Bún tôm Huế", price:12.80},
  {index:50, name:"Fried Sliced Sea Bass Fillet, Homemade Fish Cake & Tofu Bun Hue", nameVN:"Bún cá cay (cá chiên, chả cá, đậu phụ)", price:13.80},
  {index:51, name:"Special Bun Hue (King prawn, chicken, slow cooked brisket beef & sliced rare beef)", nameVN:"Bún Huế đặc biệt (tôm, gà, bò chín, bò tái)", price:12.80},
  {index:52, name:"Mixed Seafood Bun Hue (King prawn, squid, green mussels)", nameVN:"Bún hải sản Huế (tôm, mực, vẹm xanh)", price:12.80},
  {index:53, name:"Tofu & Mixed Vegetable Bun Hue", nameVN:"Bún chay Huế", price:11.25},
  {name:"Flat Rice Noodle", nameVN:"Bánh phở", price:1.95},
  {name:"Vermicelli Noodle", nameVN:"Bún", price:1.95},
  {name:"Rare Beef", nameVN:"Thịt bò tái", price:2.95},
  {name:"Slow Cooked Brisket Beef", nameVN:"Thịt bò chín", price:2.95},
  {name:"Chicken", nameVN:"Thịt gà", price:2.95},
  {name:"King Prawn", nameVN:"Tôm", price:2.95},
  {name:"Squid", nameVN:"Mực", price:2.95},
  {name:"Mussel", nameVN:"Vẹm xanh", price:2.95},
  {name:"Fried Egg", nameVN:"Trứng chiên", price:1.20},
  {name:"Beansprouts, Chillies & Herbs", nameVN:"Giá, ớt và rau thơm", price:1.00},
  {index:54, name:"Grilled Pork Marinated with Lemongrass Bun", nameVN:"Bún thịt nướng", price:10.80},
  {index:55, name:"Grilled Pork & Meat Spring Rolls Bun", nameVN:"Bún chả nem thịt nướng", price:12.80},
  {index:56, name:"Meat Spring Rolls Bun", nameVN:"Bún chả nem thịt", price:10.80},
  {index:57, name:"Tofu & Mixed Vegetable Spring Rolls Bun", nameVN:"Bún chả nem chay đậu phụ", price:10.80},
  {index:58, name:"Grilled Chicken Marinated with Lemongrass Bun", nameVN:"Bún gà nướng", price:10.80},
  {index:59, name:"Stir Fried Chicken with Lemongrass & Chillies Bun", nameVN:"Bún gà xào sả ớt", price:10.80},
  {index:60, name:"Stir Fried Beef with Lemongrass & Chillies Bun", nameVN:"Bún bò xào sả ớt", price:11.25},
  {index:61, name:"Stir Fried King Prawn with Lemongrass & Chillies Bun", nameVN:"Bún tôm xào sả ớt", price:12.80},
  {index:62, name:"Stir Fried Tofu with Lemongrass & Chillies Bun", nameVN:"Bún đậu phụ xào sả ớt", price:10.80},
  {index:63, name:"Grilled Pork Marinated with Lemongrass Rice", nameVN:"Cơm thịt nướng", price:10.80},
  {index:64, name:"Grilled Chicken Marinated with Lemongrass Rice", nameVN:"Cơm gà nướng", price:10.80},
  {index:65, name:"Grilled Pork Chop with Lemongrass, Fried Egg and Rice", nameVN:"Cơm sườn nướng, trứng chiên", price:13.80},
  {index:66, name:"Vietnamese Stewed Pork Belly with Egg and Rice", nameVN:"Cơm thịt kho trứng", price:13.80},
  {index:67, name:"Vietnamese Stewed Beef Rice", nameVN:"Cơm bò kho", price:12.80},
  {index:68, name:"Roasted Crispy Pork Rice", nameVN:"Cơm thịt heo quay giòn bì", price:13.80},
  {index:69, name:"Chicken Fried Rice", nameVN:"Cơm chiên gà", price:11.25},
  {index:70, name:"Beef Fried Rice", nameVN:"Cơm chiên bò", price:11.25},
  {index:71, name:"King Prawn Fried Rice", nameVN:"Cơm chiên tôm", price:12.80},
  {index:72, name:"Mixed Meat Fried Rice (King prawn, chicken and beef)", nameVN:"Cơm chiên đặc biệt (tôm, gà, bò)", price:12.80},
  {index:73, name:"Mixed Seafood Fried Rice (King prawn, squid and mussels)", nameVN:"Cơm chiên hải sản (tôm, mực, vẹm)", price:12.80},
  {index:74, name:"Tofu & Mixed Vegetable Fried Rice", nameVN:"Cơm chiên chay đậu phụ", price:10.80},
  {index:75, name:"Chicken Fried Egg Noodles", nameVN:"Mì xào thịt gà", price:11.25},
  {index:76, name:"Beef Fried Egg Noodles", nameVN:"Mì xào thịt bò", price:11.25},
  {index:77, name:"King Prawn Fried Egg Noodles", nameVN:"Mì xào tôm", price:12.80},
  {index:78, name:"Special Fried Egg Noodles (King prawn, chicken & beef)", nameVN:"Mì xào đặc biệt (tôm, gà, bò)", price:12.80},
  {index:79, name:"Mixed Seafood Fried Egg Noodles (King prawn, squid & mussels)", nameVN:"Mì xào hải sản (tôm, mực, vẹm)", price:12.80},
  {index:80, name:"Bean Sprouts & Onions Fried Egg Noodles", nameVN:"Mì xào giá", price:7.80},
  {index:81, name:"Tofu & Mixed Vegetable Fried Egg Noodles", nameVN:"Mì xào chay đậu phụ", price:10.80},
  {index:82, name:"Chicken Fried Flat Rice Noodles", nameVN:"Phở xào thịt gà", price:11.25},
  {index:83, name:"Beef Fried Flat Rice Noodles", nameVN:"Phở xào thịt bò", price:11.25},
  {index:84, name:"King Prawn Fried Flat Rice Noodles", nameVN:"Phở xào tôm", price:12.80},
  {index:85, name:"Special Fried Flat Rice Noodles (King prawn, chicken & beef)", nameVN:"Phở xào đặc biệt (tôm, gà, bò)", price:12.80},
  {index:86, name:"Mixed Seafood Fried Flat Rice Noodles (King prawn, squid & mussels)", nameVN:"Phở xào hải sản (tôm, mực, vẹm)", price:12.80},
  {index:87, name:"Bean Sprouts & Onions Fried Flat Rice Noodles", nameVN:"Phở xào giá", price:7.80},
  {index:88, name:"Tofu & Mixed Vegetable Fried Flat Rice Noodles", nameVN:"Phở xào chay đậu phụ", price:10.80},
  {index:89, name:"Clay Pot Mekong Catfish", nameVN:"Cá kho tộ", price:12.80},
  {index:90, name:"Camfried Beef", nameVN:"Bò lửa hồng", price:12.80},
  {index:91, name:"Shaking Beef", nameVN:"Bò lúc lắc", price:13.80},
  {index:92, name:"Deep Fried Crispy Fillet Sea Bass", nameVN:"Cá chiên mắm xoài", price:12.80},
  {index:93, name:"Vietnamese Fried Squid with Onion, Celery, Tomatoes and Chillies Paste", nameVN:"Mực xào sả ớt", price:11.80},
  {index:94, name:"Stewed Tofu with Mushroom", nameVN:"Đậu phụ kho", price:10.80},
  {index:95, name:"Fried Chicken with Lemongrass and Chillies", nameVN:"Gà xào sả ớt", price:11.80},
  {index:96, name:"Wok Fried Aubergine with Tofu and Chillies Paste", nameVN:"Cà tím, đậu phụ xào cay", price:10.80},
  {index:97, name:"Beef Curry", nameVN:"Cà ri bò", price:12.80},
  {index:98, name:"Chicken Curry", nameVN:"Cà ri gà", price:11.80},
  {index:99, name:"Lamb Curry", nameVN:"Cà ri cừu", price:13.80},
  {index:100, name:"Tofu & Mixed Vegetable Curry", nameVN:"Cà ri chay đậu phụ", price:11.80},
  {index:101, name:"Chicken Fried Rice (Kid)", nameVN:"Cơm rang gà", price:7.50},
  {index:102, name:"Deep Fried Chicken Wings & Chips", nameVN:"Cánh gà khoai tây chiên", price:7.50},
  {index:103, name:"Chicken Pho (Kid)", nameVN:"Phở gà", price:7.50},
  {index:104, name:"Beef Pho (Kid)", nameVN:"Phở bò", price:7.50},
    // --- EXTRA DISHES ---
  {name:"Bowl of Beef Broth with Green Onion", nameVN:"Nước dùng bò với hành lá", price:1.95},
  {name:"Bowl of Beef Broth with Egg Yolk", nameVN:"Nước dùng bò với trứng", price:2.50},
  {name:"Egg in Spicy Soy Sauce (for two)", nameVN:"Trứng sốt tương cay", price:3.50},
  {name:"Jasmine Rice", nameVN:"Cơm trắng", price:2.90},
  {name:"Egg Fried Rice", nameVN:"Cơm chiên trứng", price:3.90}
];
